# Generated by Django 2.2.12 on 2020-04-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_modelaline"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakeStuff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isValid", models.BooleanField()),
            ],
        ),
    ]
