# Generated by Django 2.2.12 on 2020-04-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_modelaline_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelaline',
            name='name',
        ),
    ]
