# Generated by Django 2.2.12 on 2020-04-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_modelaline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='new_field',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
